export const CONTACTS_LIST = [
  {
    id: 1,
    name: "Elma Herring",
    email: "elmaherring@unq.com",
    phone: "+1 (913) 497-2020",
    role: "Owner",
  },
  {
    id: 2,
    name: "Knapp Berry",
    email: "knappberry@unq.com",
    phone: "+1 (951) 472-2967",
    role: "Owner",
  },
  {
    id: 3,
    name: "Bell Burgess",
    email: "bellburgess@unq.com",
    phone: "+1 (887) 478-2693",
    role: "Owner",
  },
  {
    id: 4,
    name: "Hobbs Ferrell",
    email: "hobbsferrell@unq.com",
    phone: "+1 (862) 581-3022",
    role: "Owner",
  },
  {
    id: 5,
    name: "Marylou Medina",
    email: "maryloumedina@unq.com",
    phone: "+1 (996) 520-2967",
    role: "Owner",
  },
  {
    id: 6,
    name: "Larson Guerra",
    email: "larsonguerra@unq.com",
    phone: "+1 (972) 566-2684",
    role: "Owner",
  },
  {
    id: 7,
    name: "Shelby Ballard",
    email: "shelbyballard@unq.com",
    phone: "+1 (824) 467-3579",
    role: "Owner",
  },
  {
    id: 8,
    name: "Lea Faulkner",
    email: "leafaulkner@unq.com",
    phone: "+1 (899) 528-3402",
    role: "Owner",
  },
  {
    id: 9,
    name: "Cecelia Wolf",
    email: "ceceliawolf@unq.com",
    phone: "+1 (862) 507-3140",
    role: "Owner",
  },
  {
    id: 10,
    name: "Melva Nixon",
    email: "melvanixon@unq.com",
    phone: "+1 (901) 444-3081",
    role: "Owner",
  },
  {
    id: 11,
    name: "Bernard Chambers",
    email: "bernardchambers@unq.com",
    phone: "+1 (831) 539-3366",
    role: "Owner",
  },
  {
    id: 12,
    name: "Wendi Bender",
    email: "wendibender@unq.com",
    phone: "+1 (868) 414-2720",
    role: "Owner",
  },
  {
    id: 13,
    name: "Wall Stewart",
    email: "wallstewart@unq.com",
    phone: "+1 (814) 558-3191",
    role: "Owner",
  },
  {
    id: 14,
    name: "Howell Gilbert",
    email: "howellgilbert@unq.com",
    phone: "+1 (926) 512-3631",
    role: "Owner",
  },
  {
    id: 15,
    name: "Nguyen Maxwell",
    email: "nguyenmaxwell@unq.com",
    phone: "+1 (838) 469-2152",
    role: "Owner",
  },
  {
    id: 16,
    name: "Norris Hendricks",
    email: "norrishendricks@unq.com",
    phone: "+1 (818) 563-2900",
    role: "Owner",
  },
  {
    id: 17,
    name: "Salinas Mcleod",
    email: "salinasmcleod@unq.com",
    phone: "+1 (888) 413-3775",
    role: "Owner",
  },
  {
    id: 18,
    name: "Michelle Barrett",
    email: "michellebarrett@unq.com",
    phone: "+1 (988) 446-2594",
    role: "Owner",
  },
  {
    id: 19,
    name: "Burke Barlow",
    email: "burkebarlow@unq.com",
    phone: "+1 (965) 492-2552",
    role: "Owner",
  },
  {
    id: 20,
    name: "Rosie Cummings",
    email: "rosiecummings@unq.com",
    phone: "+1 (845) 456-2237",
    role: "Owner",
  },
  {
    id: 21,
    name: "Sanford Frye",
    email: "sanfordfrye@unq.com",
    phone: "+1 (936) 581-3494",
    role: "Owner",
  },
  {
    id: 22,
    name: "Janna Peck",
    email: "jannapeck@unq.com",
    phone: "+1 (824) 512-2437",
    role: "Owner",
  },
  {
    id: 23,
    name: "Lorraine Sykes",
    email: "lorrainesykes@unq.com",
    phone: "+1 (959) 422-3635",
    role: "Owner",
  },
  {
    id: 24,
    name: "Vicki Fulton",
    email: "vickifulton@unq.com",
    phone: "+1 (916) 455-2402",
    role: "Owner",
  },
  {
    id: 25,
    name: "Massey Moody",
    email: "masseymoody@unq.com",
    phone: "+1 (840) 453-3811",
    role: "Owner",
  },
  {
    id: 26,
    name: "Grant Berg",
    email: "grantberg@unq.com",
    phone: "+1 (837) 554-3706",
    role: "Owner",
  },
  {
    id: 27,
    name: "Hawkins Winters",
    email: "hawkinswinters@unq.com",
    phone: "+1 (945) 469-2432",
    role: "Owner",
  },
  {
    id: 28,
    name: "Frazier Davidson",
    email: "frazierdavidson@unq.com",
    phone: "+1 (854) 558-2637",
    role: "Owner",
  },
  {
    id: 29,
    name: "Francine Cervantes",
    email: "francinecervantes@unq.com",
    phone: "+1 (923) 520-2916",
    role: "Owner",
  },
  {
    id: 30,
    name: "Francis Perez",
    email: "francisperez@unq.com",
    phone: "+1 (885) 461-3054",
    role: "Owner",
  },
  {
    id: 31,
    name: "Francis Perez",
    email: "francisperez@unq.com",
    phone: "+1 (885) 461-3054",
    role: "Owner",
  },
];

export const COLUMN_DATA = [
  {
    title: "Name & Role",
    dataIndex: "name",
    key: "title",
    width: "40%",
  },
  {
    title: "Email",
    dataIndex: "email",
    key: "description",
    width: "50%",
  },
  {
    dataIndex: "icon_button",
    key: "icon_button",
    title: "",
    width: "10%",
  },
];
